# This file was generated by GoReleaser. DO NOT EDIT.
cask "sf" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "e093e572f95a4f4ce25e3e3efeca53682d26d72f2a03e43ba671aeef80a4d049"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c2b8ae29cb0bdbf32be538572ffb9ad839dc0f6a2ab9dfaeed0cc3cc0c5c50e"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ddf466e3d75512b66f358819d8322dd42ae1337fc389dcc1b6f590fe45c880b"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00d4d1411e1c8174048bc31b29628fc7d799d44eabfb6959b6f77f51077483c8"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sf"
  desc "Structural code context for LLM coding agents — the sf CLI"
  homepage "https://github.com/sofia-ctx/sofia"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sf"

  # No zap stanza required

end
