# This file was generated by GoReleaser. DO NOT EDIT.
cask "sf" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "4aeac2a95a0f50bef721757f0306916f22616834d386d78b3fd906c99de4c53b"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f86f2377fef4335355e7fdf474c65cb018a514c757d5e67db5dd892de275824e"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e63eb267f26c504092c720e9aa0bd5b17e467179a2da6e49205e21ccfc9692cd"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "777a726be59834a95768f9a8775613b3b5434bce92e55271b33bd5580c80d843"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sf"
  desc "Structural code context for LLM coding agents — the sf CLI"
  homepage "https://github.com/sofia-ctx/sofia"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sf"

  # No zap stanza required

end
