# This file was generated by GoReleaser. DO NOT EDIT.
cask "sf" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "b07561ea04d5610ac0044f813f4f1278f4bde4c32098235f88262e000a6e5cfd"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "54d93f9ecae063ebf0591c386402d4e27c24360a3151359b10ce5cf336cc03b5"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b21c61c039c22730b61183e9a879b8011f920842610159c775094d7d04608c10"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3709c35edf42a35f185193e23186a7a63d31f04c7fb5938260cb332e33ec2a72"
      url "https://github.com/sofia-ctx/sofia/releases/download/v#{version}/sf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sf"
  desc "Structural code context for LLM coding agents — the sf CLI"
  homepage "https://github.com/sofia-ctx/sofia"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sf"

  # No zap stanza required

end
